# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
         AppBundle\Entity\User:
            algorithm: bcrypt



    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/club/admin, roles: ROLE_ADMIN }
        - { path: ^/club, roles: ROLE_PLAYER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_PLAYER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_PLAYER]

    firewalls:


        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            # this firewall applies to all URLs
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: clubIndex
            logout:
                path: /logout
                target: /

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
